/**
 * Compute audit stats for the CEO Shadow corpus and render a markdown
 * report. RYA-845.
 */

import type { DecisionEvent } from './types.js';

export interface AuditReport {
  total: number;
  byCategory: Record<string, number>;
  bySourceType: Record<string, number>;
  bySourceRole: Record<string, number>;
  highStakes: number;
  routine: number;
  highStakesByCategory: Record<string, number>;
  routineByCategory: Record<string, number>;
  ceoDecisions: number;
  negativeExamples: number;
  silentStall: number;
  declineByOmission: number;
  earliest: string | null;
  latest: string | null;
  perMonth: Record<string, number>;
  withDispatchTarget: number;
  governanceFailureEvents: number;
  governanceFailureByHub: Record<string, number>;
  taggedTags: Record<string, number>;
  uniqueIssues: number;
  uniqueParents: number;
  /** CEO comment-event count broken down by language (heuristic CJK presence). */
  ceoCommentLangZh: number;
  ceoCommentLangEn: number;
}

function hasCjk(s: string | null | undefined): boolean {
  if (!s) return false;
  // Common CJK Unified Ideographs block.
  return /[一-鿿]/.test(s);
}

export function computeAudit(events: DecisionEvent[]): AuditReport {
  const byCategory: Record<string, number> = {};
  const bySourceType: Record<string, number> = {};
  const bySourceRole: Record<string, number> = {};
  const perMonth: Record<string, number> = {};
  const taggedTags: Record<string, number> = {};
  const highStakesByCategory: Record<string, number> = {};
  const routineByCategory: Record<string, number> = {};
  const governanceFailureByHub: Record<string, number> = {};
  const issueKeys = new Set<string>();
  const parentKeys = new Set<string>();

  let highStakes = 0;
  let routine = 0;
  let ceoDecisions = 0;
  let negative = 0;
  let silentStall = 0;
  let declineByOmission = 0;
  let withDispatch = 0;
  let governanceFailure = 0;
  let ceoCommentLangZh = 0;
  let ceoCommentLangEn = 0;
  let earliest: string | null = null;
  let latest: string | null = null;

  for (const e of events) {
    byCategory[e.category] = (byCategory[e.category] ?? 0) + 1;
    bySourceType[e.source.source_type] = (bySourceType[e.source.source_type] ?? 0) + 1;
    bySourceRole[e.issue.creator_role] = (bySourceRole[e.issue.creator_role] ?? 0) + 1;
    if (e.is_high_stakes) {
      highStakes++;
      highStakesByCategory[e.category] = (highStakesByCategory[e.category] ?? 0) + 1;
    } else {
      routine++;
      routineByCategory[e.category] = (routineByCategory[e.category] ?? 0) + 1;
    }
    if (e.is_ceo_decision) ceoDecisions++;
    if (e.negative_example) negative++;
    if (e.decision.dispatch_target) withDispatch++;

    if (e.tags.includes('silent-stall')) silentStall++;
    if (e.tags.includes('decline-by-omission')) declineByOmission++;

    if (e.source.source_type === 'comment') {
      if (hasCjk(e.decision.comment_body)) ceoCommentLangZh++;
      else ceoCommentLangEn++;
    }

    issueKeys.add(e.issue.key);
    if (e.issue.parent_key) parentKeys.add(e.issue.parent_key);

    const month = e.ts.slice(0, 7);
    perMonth[month] = (perMonth[month] ?? 0) + 1;

    for (const t of e.tags) {
      taggedTags[t] = (taggedTags[t] ?? 0) + 1;
      if (t.startsWith('governance-failure:')) {
        governanceFailure++;
        const hub = t.split(':')[1];
        governanceFailureByHub[hub] = (governanceFailureByHub[hub] ?? 0) + 1;
      } else if (t.startsWith('governance-hub:')) {
        governanceFailure++;
      }
    }

    if (!earliest || e.ts < earliest) earliest = e.ts;
    if (!latest || e.ts > latest) latest = e.ts;
  }

  return {
    total: events.length,
    byCategory,
    bySourceType,
    bySourceRole,
    highStakes,
    routine,
    highStakesByCategory,
    routineByCategory,
    ceoDecisions,
    negativeExamples: negative,
    silentStall,
    declineByOmission,
    earliest,
    latest,
    perMonth,
    withDispatchTarget: withDispatch,
    governanceFailureEvents: governanceFailure,
    governanceFailureByHub,
    taggedTags,
    uniqueIssues: issueKeys.size,
    uniqueParents: parentKeys.size,
    ceoCommentLangZh,
    ceoCommentLangEn,
  };
}

function pct(n: number, total: number): string {
  if (!total) return '0.0%';
  return `${((n / total) * 100).toFixed(1)}%`;
}

export function renderAuditMarkdown(audit: AuditReport): string {
  const lines: string[] = [];
  lines.push('# CEO Shadow Corpus — Audit Report');
  lines.push('');
  lines.push('> Generated by `src/coop/ceo-shadow/cli.ts audit`. RYA-845.');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`- **Total decision events**: ${audit.total}`);
  lines.push(`- **Unique issues touched**: ${audit.uniqueIssues}`);
  lines.push(`- **Unique parent (hub) issues**: ${audit.uniqueParents}`);
  lines.push(`- **Time coverage**: ${audit.earliest ?? 'n/a'} → ${audit.latest ?? 'n/a'}`);
  lines.push(`- **CEO decisions (positive)**: ${audit.ceoDecisions} (${pct(audit.ceoDecisions, audit.total)})`);
  lines.push(`- **Negative examples**: ${audit.negativeExamples} (${pct(audit.negativeExamples, audit.total)}) — silent-stall=${audit.silentStall}, decline-by-omission=${audit.declineByOmission}`);
  lines.push(`- **High-stakes vs routine**: ${audit.highStakes} (${pct(audit.highStakes, audit.total)}) high-stakes · ${audit.routine} (${pct(audit.routine, audit.total)}) routine`);
  lines.push(`- **Governance-failure-tagged**: ${audit.governanceFailureEvents} (${pct(audit.governanceFailureEvents, audit.total)})`);
  lines.push(`- **CEO comment language**: zh=${audit.ceoCommentLangZh}, en=${audit.ceoCommentLangEn}`);
  lines.push(`- **Comments with parsed dispatch target**: ${audit.withDispatchTarget}`);
  lines.push('');
  lines.push('## By category');
  lines.push('');
  for (const [k, v] of Object.entries(audit.byCategory).sort((a, b) => b[1] - a[1])) {
    lines.push(`- ${k}: ${v} (${pct(v, audit.total)})`);
  }
  lines.push('');
  lines.push('## By source type');
  lines.push('');
  for (const [k, v] of Object.entries(audit.bySourceType).sort((a, b) => b[1] - a[1])) {
    lines.push(`- ${k}: ${v} (${pct(v, audit.total)})`);
  }
  lines.push('');
  lines.push('## By issue creator role');
  lines.push('');
  for (const [k, v] of Object.entries(audit.bySourceRole).sort((a, b) => b[1] - a[1])) {
    lines.push(`- ${k}: ${v} (${pct(v, audit.total)})`);
  }
  lines.push('');
  lines.push('## High-stakes split by category');
  lines.push('');
  lines.push('| category | high-stakes | routine |');
  lines.push('|---|---|---|');
  const allCats = new Set([...Object.keys(audit.highStakesByCategory), ...Object.keys(audit.routineByCategory)]);
  for (const cat of [...allCats].sort()) {
    lines.push(`| ${cat} | ${audit.highStakesByCategory[cat] ?? 0} | ${audit.routineByCategory[cat] ?? 0} |`);
  }
  lines.push('');
  lines.push('## Governance-failure exhaust by hub');
  lines.push('');
  for (const [k, v] of Object.entries(audit.governanceFailureByHub).sort((a, b) => b[1] - a[1])) {
    lines.push(`- ${k}: ${v}`);
  }
  lines.push('');
  lines.push('## Decisions per month');
  lines.push('');
  for (const [k, v] of Object.entries(audit.perMonth).sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
    lines.push(`- ${k}: ${v}`);
  }
  lines.push('');
  lines.push('## Top tags');
  lines.push('');
  const sortedTags = Object.entries(audit.taggedTags).sort((a, b) => b[1] - a[1]);
  for (const [k, v] of sortedTags.slice(0, 20)) {
    lines.push(`- ${k}: ${v}`);
  }
  lines.push('');
  lines.push('## Notes');
  lines.push('');
  lines.push('- Time-coverage caveat: the team only began using Linear on/around 2026-03-23, so the corpus reflects ~6 weeks of decisions despite the 6-month query window.');
  lines.push('- Predictor consumers: see `src/coop/ceo-shadow/README.md` for the stable schema. New tag values may appear without notice; new top-level fields and new `category` enum values are minor / breaking changes respectively.');
  lines.push('- Sensitivity: corpus lives only at `~/.aos/ceo-shadow/`. Do not publish.');
  return lines.join('\n');
}
