/**
 * Noise filter: titles that should never be auto-dispatched or auto-reviewed.
 *
 * Two classes of noise:
 *
 * 1. Proactive machinery (idea proposals, board votes, exploration hubs).
 *    Generated by the proactive subsystem. Only the proactive heartbeat
 *    itself should dispatch these — gated by the per-role weekly cadence.
 *
 * 2. `[to decide]` issues. These await CEO decision; agents must not
 *    pick them up. handleDispatch in dispatch.ts also rejects them, but
 *    autoDispatchFromBacklog calls agentStartCommand directly and bypasses
 *    that guard — so the noise filter is the canonical block on the
 *    Backlog scan path.
 *
 * 3. `Daily triage:*` issues (RYA-1205). Created and dispatched in one shot
 *    by ceoOfficeTriageHeartbeat — no other path may dispatch them. Before
 *    this filter, heartbeatAssignUnowned saw them as unassigned Todo issues
 *    and only the 10-min disp-any dedup window stood between the two paths.
 */

// RYA-1205: matches issues created by ceoOfficeTriageHeartbeat. Shared with
// the trigger itself, which must exclude prior triage issues from its
// new-item keyset (a finished triage landing In Review fed its own trigger:
// 4 dispatches in ~2.5h on 2026-06-10).
const TRIAGE_TITLE_RE = /^Daily triage:/i;

export function isTriageIssue(title: string | null | undefined): boolean {
  if (!title) return false;
  return TRIAGE_TITLE_RE.test(title);
}

const NOISE_PATTERNS: RegExp[] = [
  /^\[proactive[\] ]/i,        // [proactive], [proactive idea], [proactive ...]
  /^\[idea\]/i,
  /^\s*\[to decide\]/i,        // [to decide] issues await CEO — never auto-dispatch
  /^Proactive(:| Hub| idea)/i,
  /\bvote on RYA-/i,
  /Strategic Exploration Hub/i,
  /^Set up proactive/i,
  /Board vote protocol/i,
  /Propose 2-3 .*transformative/i,
  TRIAGE_TITLE_RE,             // Daily triage:* — only ceoOfficeTriageHeartbeat dispatches these
];

export function isNoiseIssue(title: string | null | undefined): boolean {
  if (!title) return false;
  return NOISE_PATTERNS.some(re => re.test(title));
}
